import Foundation

/// Shared golden vectors — numeric values copied from
/// `app/src/test/java/app/gridfix/android/GoldenVectors.kt` (generated by kmp/gen_golden.py).
///
/// Distance/bearing legs are fully loaded for `GeodesyGoldenTests`.
/// UTM / MGRS / convergence CSVs stay in Kotlin until the MGRS port lands;
/// keep this file as the single iOS destination for the generator output.
public enum GoldenVectors {

    public static let tolUtmMeters = 0.5
    public static let tolLatLonDegrees = 1e-05
    public static let tolDistanceMeters = 0.5
    public static let tolBearingDegrees = 0.01
    public static let tolConvergenceDegrees = 1e-06

    public struct Leg: Equatable, Sendable {
        public let name: String
        public let fromLat: Double
        public let fromLon: Double
        public let toLat: Double
        public let toLon: Double
        public let meters: Double
        public let bearing: Double
    }

    /// name,fromLat,fromLon,toLat,toLon,meters,bearing — exact copy of DISTANCE_CSV.
    private static let distanceCSV = """
        zero,24.4539,54.3773,24.4539,54.3773,0.0,0.0
        course-ring-25m,24.4539,54.3773,24.45412,54.3773,24.3683,0.0
        short-100m,24.4539,54.3773,24.4548,54.3773,99.6883,0.0
        arrival-50m,24.4539,54.3773,24.4539,54.37779,49.6819,89.999899
        leg-1km-north,24.4539,54.3773,24.46293,54.3773,1000.2069,0.0
        leg-1km-east,24.4539,54.3773,24.4539,54.38722,1005.8058,89.997947
        leg-10km-east,24.4539,54.3773,24.4539,54.4763,10037.779,89.979509
        leg-10km-north,24.4539,54.3773,24.5442,54.3773,10002.1231,0.0
        leg-25km-diag,24.4539,54.3773,24.6139,54.5573,25431.2521,45.785372
        cross-equator,-0.5,36.9,0.5,36.9,110574.304,0.0
        high-lat,64.8378,-147.7164,64.9378,-147.5164,14631.1681,40.267859
        southern,-33.8568,151.2152,-33.9568,151.3152,14441.9443,140.206572
        antimeridian,1.0,179.95,1.0,-179.95,11130.265,89.999127
        vincenty-canonical,-37.9510334167,144.4248678889,-37.6528211389,143.9264955278,54972.2711,306.868159
        one-degree-lat-eq,0.0,0.0,1.0,0.0,110574.3886,0.0
        one-degree-lat-45,45.0,0.0,46.0,0.0,111141.5485,0.0
        one-degree-lon-eq,0.0,0.0,0.0,1.0,111319.4908,90.0
        """

    public static let distance: [Leg] = {
        distanceCSV
            .split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .map { line in
                let c = line.split(separator: ",", omittingEmptySubsequences: false).map(String.init)
                precondition(c.count == 7, "bad distance row: \(line)")
                return Leg(
                    name: c[0],
                    fromLat: Double(c[1])!,
                    fromLon: Double(c[2])!,
                    toLat: Double(c[3])!,
                    toLon: Double(c[4])!,
                    meters: Double(c[5])!,
                    bearing: Double(c[6])!
                )
            }
    }()
}
